jmix.core.additional-stores=customers

main.datasource.url=jdbc:postgresql://localhost/jmixpmdata_03
main.datasource.username=root
main.datasource.password=root

main.liquibase.change-log=com/company/jmixpmdata/liquibase/changelog.xml

customers.datasource.url=jdbc:postgresql://localhost/customers_03
customers.datasource.username=root
customers.datasource.password=root

customers.liquibase.change-log=com/company/jmixpmdata/liquibase/customers-changelog.xml

jmix.ui.login-view-id=LoginView
jmix.ui.main-view-id=MainView
jmix.ui.menu-config=com/company/jmixpmdata/menu.xml
jmix.ui.composite-menu=true

ui.login.defaultUsername=admin
ui.login.defaultPassword=admin

spring.security.oauth2.authorizationserver.client.myclient.registration.client-id=my-client
spring.security.oauth2.authorizationserver.client.myclient.registration.client-secret={noop}my-secret
spring.security.oauth2.authorizationserver.client.myclient.registration.authorization-grant-types=client_credentials
spring.security.oauth2.authorizationserver.client.myclient.registration.client-authentication_methods=client_secret_basic
spring.security.oauth2.authorizationserver.client.myclient.token.access-token-format=reference
spring.security.oauth2.authorizationserver.client.myclient.token.access-token-time-to-live=24h

jmix.rest.services-config=com/company/jmixpmdata/rest-services.xml
jmix.rest.queries-config=com/company/jmixpmdata/rest-queries.xml

jmix.resource-server.authenticated-url-patterns=/rest/**

jmix.core.available-locales=en,ru

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=false

logging.level.org.atmosphere=warn

# 'debug' level logs SQL generated by EclipseLink ORM
logging.level.eclipselink.logging.sql=info

# 'debug' level logs data store operations
logging.level.io.jmix.core.datastore=info

# 'debug' level logs access control constraints
logging.level.io.jmix.core.AccessLogger=debug

# 'debug' level logs all Jmix debug output
logging.level.io.jmix=info

# 'debug' or 'trace' levels help to troubleshoot security problems
logging.level.org.springframework.security=info

main.liquibase.enabled=false
jmix.core.fetch-plans-config=com/company/jmixpmdata/fetch-plans.xml

eclipselink.cache.shared.User=true
eclipselink.cache.size.User=500

jmix.core.session.maximum-sessions-per-user=1